### ISSUE TITLE
Feature: Fadein distance

### ISSUE THREAD

**Issue by Konngitas** [Konngitas/StaticGatheringMarkersPlugin#1]
Make markers show up only when the player is near. Its too much clutter to show all markers at once

**Comment by haroldiedema** [comment]
Have a look at the new `MaxVisibleDistance` field of markers. See https://github.com/una-xiv/umbra/commit/6ed3a69aad1035a38a55cab61caa18de94f4b7c3 for some example implementations.

The config variable is already in the default list.

**Comment by Konngitas** [comment]
Yep! I read the update note :) Thanks

**Comment by Konngitas** [comment]
Implemented in 2b762abc8b8baa246c505507c6ec74f32af90b50
